### ISSUE TITLE
Cryptocurrency demo (ERROR: Transaction has not been accepted to the blockchain/Request failed with status code 500)

### ISSUE THREAD

**Issue by BekirHadzic** [exonum/exonum#1228]
Hi, I was facing some issues with cryptocurrency demo. I followed the step-by-step guide for manually starting the cryptocurrency service on four nodes. The problem is following, every time I set up the nodes and started npm, I should have an option from my web browser on my local machine to start the Cryptocurrency demo which you will be able to see in the pictures below. Basically, when everything is started I have 2 options, one for login and another one for registering. When I want to register a name, it keeps giving me an error about transaction not being accepted to the blockchain. However, when I start the service with docker command I keep getting another error 500 which means internal server error. You will be able to see everything in the screenshots. 

![screenshot from 2019-01-07 11-56-30](https://user-images.githubusercontent.com/44608433/51246830-a3c11780-198b-11e9-9160-dae1e2169c3e.png)
![screenshot from 2019-01-16 12-12-38](https://user-images.githubusercontent.com/44608433/51246900-d408b600-198b-11e9-8537-e82e12e8da0f.png)
![screenshot from 2019-01-16 12-08-24](https://user-images.githubusercontent.com/44608433/51246824-a0c62700-198b-11e9-82a4-de5bbfa0bdbd.png)
![screenshot from 2019-01-16 12-12-20](https://user-images.githubusercontent.com/44608433/51246909-db2fc400-198b-11e9-8aaf-48d06f86fbe6.png)
![screenshot from 2019-01-16 12-27-00](https://user-images.githubusercontent.com/44608433/51246916-dff47800-198b-11e9-892d-9b5e20f1a893.png)
![screenshot from 2019-01-16 12-08-27](https://user-images.githubusercontent.com/44608433/51246818-9d32a000-198b-11e9-9ab5-501450d0be96.png)

**Comment by ivan-ochc** [comment]
@BekirHadzic, hi. I can't reproduce your issue with 0.9.6. Seems that Exonum nodes weren't started properly. Could you please provide logs? To see logs start nodes in such way: `RUST_LOG=info exonum-cryptocurrency-advanced run --node-config example/node_1_cfg.toml --db-path example/db1 --public-api-address 0.0.0.0:82001`

**Comment by 5mirok5** [comment]
I have this error too

**Comment by BekirHadzic** [comment]
@ivan-ochc thank you very much, but I already fixed it. It seems that there was mistake made by me during the process of configuring the nodes. I deleted the example folder inside **/cryptocurrency-advanced/backend/example** and the node_modules inside **/cryptocurrency-advanced/frontend/node_modules** and then started the with cryptocurrency demo tutorial from beginning. This time I am running 4 nodes at the same time, but at the time when I posted the issue I was running only one node, so that can be the reason why the transaction could not be accepted to the blockchain. 

@5mirok5 If you still have those problems, feel free to ask

**Comment by 5mirok5** [comment]
@BekirHadzic I use image from docker, but I have same error

**Comment by BekirHadzic** [comment]
@5mirok5 try to do it manually in that case. I was also facing issues when using a docker image. Cryptocurrency-advanced provides really good manual instructions in the readme file.

#### Install and run

Below you will find a step-by-step guide to starting the cryptocurrency
service on 4 nodes on the local machine.

Build the project:

```sh
cd examples/cryptocurrency-advanced/backend

cargo install
```

Generate template (stay inside backend and copy/paste the instructions):



```sh
mkdir example

exonum-cryptocurrency-advanced generate-template example/common.toml --validators-count 4
```

Generate public and secrets keys for each node (later on, you will see files inside the example folder):

```sh
exonum-cryptocurrency-advanced generate-config example/common.toml  example/pub_1.toml example/sec_1.toml --peer-address 127.0.0.1:6331

exonum-cryptocurrency-advanced generate-config example/common.toml  example/pub_2.toml example/sec_2.toml --peer-address 127.0.0.1:6332

exonum-cryptocurrency-advanced generate-config example/common.toml  example/pub_3.toml example/sec_3.toml --peer-address 127.0.0.1:6333

exonum-cryptocurrency-advanced generate-config example/common.toml  example/pub_4.toml example/sec_4.toml --peer-address 127.0.0.1:6334
```

Finalize configs:

```sh
exonum-cryptocurrency-advanced finalize --public-api-address 0.0.0.0:8200 --private-api-address 0.0.0.0:8091 example/sec_1.toml example/node_1_cfg.toml --public-configs example/pub_1.toml example/pub_2.toml example/pub_3.toml example/pub_4.toml

exonum-cryptocurrency-advanced finalize --public-api-address 0.0.0.0:8201 --private-api-address 0.0.0.0:8092 example/sec_2.toml example/node_2_cfg.toml --public-configs example/pub_1.toml example/pub_2.toml example/pub_3.toml example/pub_4.toml

exonum-cryptocurrency-advanced finalize --public-api-address 0.0.0.0:8202 --private-api-address 0.0.0.0:8093 example/sec_3.toml example/node_3_cfg.toml --public-configs example/pub_1.toml example/pub_2.toml example/pub_3.toml example/pub_4.toml

exonum-cryptocurrency-advanced finalize --public-api-address 0.0.0.0:8203 --private-api-address 0.0.0.0:8094 example/sec_4.toml example/node_4_cfg.toml --public-configs example/pub_1.toml example/pub_2.toml example/pub_3.toml example/pub_4.toml
```

Run nodes (at this part open 4 terminals, but make sure that you are inside backend, because if not, you won't be able to run the nodes):

```sh
exonum-cryptocurrency-advanced run --node-config example/node_1_cfg.toml --db-path example/db1 --public-api-address 0.0.0.0:8200

exonum-cryptocurrency-advanced run --node-config example/node_2_cfg.toml --db-path example/db2 --public-api-address 0.0.0.0:8201

exonum-cryptocurrency-advanced run --node-config example/node_3_cfg.toml --db-path example/db3 --public-api-address 0.0.0.0:8202

exonum-cryptocurrency-advanced run --node-config example/node_4_cfg.toml --db-path example/db4 --public-api-address 0.0.0.0:8203
```



Install frontend dependencies (open again a new terminal and make sure that you are in cryptocurrency-advanced/frontend):

```sh
cd frontend

npm install
```

Build sources:

```sh
npm run build
```

Run the application (after starting npm command below, copy the address 127.0.0.1:8280 and paste it in your browser):

```sh
npm start -- --port=8280 --api-root=http://127.0.0.1:8200
```

`--port` is a port for Node.JS app.

`--api-root` is a root URL of public API address of one of nodes.

Now it should be able to work, but if you still have some issues, maybe you could take some screenshots to provide more information

**Comment by ivan-ochc** [comment]
@5mirok5, do still have a problem with cryptocurrency-advanced demo?

**Comment by vitvakatu** [comment]
@BekirHadzic great, feel free to create an issues if you face some problems. Closing this for now
